// Generates supabase/seed.sql from the bundled catalog + canonical scoring rules.
// Run: npx tsx scripts/gen-seed.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { writeFileSync } from 'node:fs'
import sheets from '../src/data/products.json'
import pillows from '../src/data/pillows.json'
import comforters from '../src/data/comforters.json'
import { SCORING_RULES } from '../src/lib/scoringRules'
import { QUESTION_SEED, SECTION_LONG_TO_SHORT } from '../src/lib/questionData'

const esc = (s: string) => s.replace(/'/g, "''")
const S = (v: string | null | undefined) => (v == null ? 'null' : `'${esc(v)}'`)
const N = (v: number | null | undefined) => (v == null ? 'null' : String(v))
const J = (v: unknown) => `'${esc(JSON.stringify(v ?? null))}'::jsonb`

const out: string[] = []
out.push('-- GENERATED by scripts/gen-seed.ts — do not edit by hand.')
out.push('-- Run in the Supabase SQL editor. Resets catalog + rules; leaves responses untouched.\n')

// Idempotent migrations (covers projects created before these columns existed).
out.push('alter table products      add column if not exists material text;')
out.push('alter table products      add column if not exists weave text;')
out.push('alter table products      add column if not exists thread_count int;')
out.push('alter table products      add column if not exists fill text;')
out.push('alter table scoring_rules add column if not exists also_question_key text;')
out.push('alter table scoring_rules add column if not exists also_answer_value text;\n')

out.push('delete from question_options;')
out.push('delete from questions;')
out.push('delete from scoring_rules;')
out.push('delete from products;\n')

// ── Products ──
const PCOLS = 'category, code, name, name_zh, sku, collection, material, weave, thread_count, fill, description, description_zh, best_for, best_for_zh, attributes, ratings, sort_order, active'
out.push(`insert into products (${PCOLS}) values`)

type AnyProduct = Record<string, any>
const rows: string[] = []
let order = 0
const pushProduct = (category: string, p: AnyProduct, opts: { material?: boolean; weave?: boolean; threadCount?: boolean; fill?: boolean }) => {
  rows.push(
    `  (${S(category)}, ${S(p.product_id)}, ${S(p.name)}, ${S(p.name_zh ?? null)}, ${S(p.sku ?? null)}, ${S(p.collection ?? null)}, ` +
    `${opts.material ? S(p.material) : 'null'}, ${opts.weave ? S(p.weave) : 'null'}, ${opts.threadCount ? N(p.thread_count ?? null) : 'null'}, ${opts.fill ? S(p.fill) : 'null'}, ` +
    `${S(p.description ?? null)}, ${S(p.description_zh ?? null)}, ${J(p.best_for ?? [])}, ${J(p.best_for_zh ?? [])}, ` +
    `${J(p.attributes ?? {})}, ${J(p.ratings ?? {})}, ${order++}, true)`,
  )
}
;(sheets as AnyProduct[]).forEach(p => pushProduct('sheet', p, { material: true, weave: true, threadCount: true }))
;(comforters as AnyProduct[]).forEach(p => pushProduct('comforter', p, { fill: true }))
;(pillows as AnyProduct[]).forEach(p => pushProduct('pillow', p, { fill: true }))
out.push(rows.join(',\n') + ';\n')

// ── Scoring rules ──
const RCOLS = 'question_key, answer_value, target_category, attribute_path, operator, compare_value, points, reason, reason_zh, also_question_key, also_answer_value, active'
out.push(`insert into scoring_rules (${RCOLS}) values`)
const rrows = SCORING_RULES.map(r =>
  `  (${S(r.question_key)}, ${S(r.answer_value)}, ${S(r.target_category)}, ${S(r.attribute_path)}, ${S(r.operator)}, ${S(r.compare_value)}, ` +
  `${N(r.points)}, ${S(r.reason ?? null)}, ${S(r.reason_zh ?? null)}, ${S(r.also_question_key ?? null)}, ${S(r.also_answer_value ?? null)}, true)`,
)
out.push(rrows.join(',\n') + ';\n')

// ── Questions ──
out.push('insert into questions (key, section, question, question_zh, columns, sort_order, active) values')
const qrows = QUESTION_SEED.map((q, i) =>
  `  (${S(q.id)}, ${S(SECTION_LONG_TO_SHORT[q.section] ?? q.section)}, ${S(q.question)}, ${S(q.question_zh)}, ${N(q.columns)}, ${i}, true)`,
)
out.push(qrows.join(',\n') + ';\n')

// ── Question options (question_id resolved by key) ──
out.push('insert into question_options (question_id, value, label, label_zh, sublabel, sublabel_zh, icon_key, sort_order) values')
const orows: string[] = []
QUESTION_SEED.forEach(q => {
  q.options.forEach((o, i) => {
    orows.push(
      `  ((select id from questions where key = ${S(q.id)}), ${S(o.value)}, ${S(o.label)}, ${S(o.label_zh)}, ${S(o.sublabel)}, ${S(o.sublabel_zh)}, ${S(o.icon_key)}, ${i})`,
    )
  })
})
out.push(orows.join(',\n') + ';\n')

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n'))
console.log(`Wrote supabase/seed.sql — ${rows.length} products, ${rrows.length} scoring rules, ${qrows.length} questions, ${orows.length} options`)
